version: "3.9"
services:
  app:
    build: .
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    env_file:
      - .local.env
    ports:
      - "4000:4000"

  postgres:
    image: postgres:alpine
    env_file:
      - .local.env
    ports:
      - "5432:5432"
