version: "3.9"
services:
  sut:
    build:
      context: .
      target: test
      args:
        - POSTGRES_HOST=$POSTGRES_HOST
        - POSTGRES_DB=$POSTGRES_DB
        - POSTGRES_USER=$POSTGRES_USER
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        
    depends_on:
      - postgres_test
    environment:
      - POSTGRES_HOST
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - TOKEN_SECRET
      - BCRYPT_PASSWORD
      - SALT_ROUNDS

  postgres_test:
    image: postgres:alpine
    environment:
      - POSTGRES_HOST
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

