name: ci

on:
  push:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    environment: test
    env:
      POSTGRES_USER: ${{secrets.POSTGRES_USER}}
      POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
      POSTGRES_DB: ${{secrets.POSTGRES_DB}}
      POSTGRES_HOST: ${{secrets.POSTGRES_HOST}}
      TOKEN_SECRET: ${{secrets.TOKEN_SECRET}}
      SALT_ROUNDS: ${{secrets.SALT_ROUNDS}}
      BCRYPT_PASSWORD: ${{secrets.BCRYPT_PASSWORD}}

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Build 
        run: docker compose -f ./docker-compose.test.yaml build

      -
        name: Test
        run:  docker compose -f ./docker-compose.test.yaml up --exit-code-from sut
